webapp/movie/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, TextAreaField, URLField
from wtforms.validators import InputRequired, NumberRange


class StringListField(TextAreaField):
    def _value(self):
        if self.data:
            return "\n".join(self.data)
        else:
            return ""

    def process_formdata(self, valuelist):
        # checks valuelist contains at least 1 element, and the first element isn't falsy (i.e. empty string)
        if valuelist and valuelist[0]:
            self.data = [line.strip() for line in valuelist[0].split("\n")]
        else:
            self.data = []


class MovieForm(FlaskForm):
    title = StringField("Title", validators=[InputRequired()])
    director = StringField("Director", validators=[InputRequired()])
    year = IntegerField(
        "Year",
        validators=[
            InputRequired(),
            NumberRange(min=1878, message="Please enter a year in the format YYYY."),
        ],
    )
    cast = StringListField("Cast")
    series = StringListField("Series")
    tags = StringListField("Tags")
    description = TextAreaField("Description")
    video_link = URLField("Video link")
    submit = SubmitField("Add Movie")


class EditMovieForm(MovieForm):
    title = StringField("Title")
    director = StringField("Director")
    year = IntegerField("Year")
    description = TextAreaField("Description")
    video_link = URLField("Video link")
    submit = SubmitField("Submit")


class AddTagsForm(FlaskForm):
    tags = StringListField("Tags")
    submit = SubmitField("Submit")

webapp/movie/routes.py
import datetime

from pydantic import BaseModel, validator, ValidationError
from typing import Optional

from flask import current_app
from flask import Blueprint, redirect, render_template, session, url_for, request, flash, abort
from flask_login import current_user, login_required

from webapp import db
from webapp.models import Movie, User, Tag, Cast, Series
from webapp.movie.forms import MovieForm, EditMovieForm, AddTagsForm


bp = Blueprint("movie", __name__, template_folder="templates", static_folder="static")


# --------------
# Helper Classes
# --------------


class MovieModel(BaseModel):
    """Class for parsing new movie data from a form."""

    title: str
    director: str
    year: int
    description: Optional[str] = ""
    video_link: Optional[str] = ""


def movie_rating_check(value: int, movie: MovieModel) -> int:
    if value not in range(1, 6):
        error = "Movie rating must be a whole number between 1 and 5"
        current_app.logger.critical(f"Error while rating the movie: {movie.title} - {error}")
        abort(500, error)
    return value


@bp.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@bp.errorhandler(500)
def internal_error(e):
    return render_template("500.html"), 500


@bp.errorhandler(403)
def page_forbidden(e):
    return render_template("403.html"), 500


@bp.route("/")
def home():
    if current_user.is_authenticated:
        return redirect(url_for("movie.index"))

    return render_template("home.html")


@bp.route("/index")
@login_required
def index():
    if not current_user.is_authenticated:
        flash("You must be logged in to view your profile!", "danger")
        return redirect(url_for("auth.login"))

    try:
        movies = Movie.query.filter_by(userId=current_user.id).all()
    except Exception as error:
        current_app.logger.error("Error while getting movies from the database: {}".format(error))
        abort(404, error)

    return render_template("movie.html", title="Movies Watchlist", movies_data=movies)


@bp.route("/movie/<int:movieId>", methods=["GET"])
@login_required
def movie(movieId):
    current_app.logger.info("getting the movie from the database...")
    movie = Movie.query.get_or_404(movieId)

    try:
        current_app.logger.debug("Get tags, cast and series with index: {}".format(movieId))
        tags = Tag.query.filter_by(movieId=movie.id)
        cast = Cast.query.filter_by(movieId=movie.id)
        series = Series.query.filter_by(movieId=movie.id)

    except Exception as error:
        current_app.logger.error("MovieId {} is causing an IndexError".format(movieId))
        abort(404, error)

    return render_template("movie_details.html", movie=movie, tags=tags, cast=cast, series=series)


@bp.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    """Add a new movie to the database."""

    if not current_user.is_authenticated:
        flash("You must be logged in to add a movie!", "danger")
        return redirect(url_for("auth.login"))

    user = User.query.filter_by(id=current_user.id).first()
    form = MovieForm()

    if request.method == "POST":
        try:
            movie_data = MovieModel(title=form.title.data, director=form.director.data, year=form.year.data)
            movie = Movie(title=movie_data.title, director=movie_data.director, year=movie_data.year, userId=user.id)
            db.session.add(movie)
            db.session.commit()

        except ValidationError as e:
            flash("Error with movie data submitted!")
            db.session.rollback()

        if form.validate_on_submit():
            try:
                for actor in form.cast.data:
                    cast = Cast(actor=actor, movieId=movie.id)
                    db.session.add(cast)

                for tag in form.tags.data:
                    tag = Tag(tag=tag, movieId=movie.id)
                    db.session.add(tag)

                for serial in form.series.data:
                    single_serial = Series(series=serial, movieId=movie.id)
                    db.session.add(single_serial)

                if form.description.data != "":
                    movie.description = form.description.data

                if form.video_link.data != "":
                    movie.video_link = form.video_link.data

                db.session.commit()
                flash(f"Added new movie ({movie.title})!")
                current_app.logger.info(f"Movie ({movie.title}) was added for user: {current_user.id}!")
                return redirect(url_for("movie.index"))

            except Exception as error:
                db.session.rollback()
                current_app.logger.error("MovieId {} is causing an IndexError".format(movieId))
                abort(404, error)

    return render_template("new_movie.html", title="Movies Watchlist - Add Movie", form=form)


@bp.route("/edit/<int:movieId>", methods=["GET", "POST"])
@login_required
def edit_movie(movieId):
    """Edit a movie in the database."""

    movie = Movie.query.get_or_404(movieId)
    form = EditMovieForm(obj=movie)

    if movie is None:
        abort(404)

    if movie.userId != current_user.id:
        abort(500)

    if form.validate_on_submit():
        try:
            movie.title = form.title.data
            movie.director = form.director.data
            movie.year = form.year.data
            movie.description = form.description.data
            movie.video_link = form.video_link.data

            db.session.commit()

        except Exception as e:
            db.session.rollback()
            current_app.logger.critical(f"Error while editing the movie: {movie.title} - {e}")
            current_app.logger.exception(e)
            flash("There was an error while editing your movie. Try again later.", "danger")
            return redirect(url_for("movie.edit_movie", movieId=movie.id))

        flash("The movie has been updated successfully!", "success")
        return redirect(url_for("movie.movie", movieId=movie.id))

    return render_template("movie_form.html", movie=movie, form=form)


@bp.route("/<int:movieId>/delete")
@login_required
def delete_movie(movieId):
    movie = Movie.query.get_or_404(movieId)

    if movie is None:
        abort(404)

    if movie.userId != current_user.id:
        abort(403)

    db.session.delete(movie)
    db.session.commit()
    flash(f"Movie ({movie.title}) was deleted!")
    current_app.logger.info(f"Movie ({movie.title}) was deleted for user: {current_user.id}!")

    return redirect(url_for("movie.index"))


@bp.route("/add/tags/<int:movieId>", methods=["GET", "POST"])
@login_required
def add_tags(movieId):
    tags = Tag.query.filter_by(movieId=movieId)
    form = AddTagsForm()

    if form.validate_on_submit():
        try:
            for tag in form.tags.data:
                tag = Tag(tag=tag, movieId=movieId)
                db.session.add(tag)
            db.session.commit()

        except Exception as e:
            db.session.rollback()
            current_app.logger.critical(f"Error while adding the tag: {tag} - {e}")
            current_app.logger.exception(e)

            flash("There was an error while adding your tag. Try again later.", "danger")
            return redirect(url_for("movie.add_tags", movieId=movieId))

        flash("Your tag has been added!", "success")
        return redirect(url_for("movie.movie", movieId=movieId))

    return render_template("tag_form.html", tags=tags, form=form)


@bp.route("/movie/<int:movieId>/delete/tags/<int:tag_id>", methods=["GET", "POST"])
@login_required
def delete_tag(tag_id, movieId):
    tag = Tag.query.filter_by(id=tag_id).first_or_404()

    try:
        db.session.delete(tag)
        db.session.commit()

    except Exception as e:
        db.session.rollback()
        current_app.logger.critical(f"Error while deleting the tag: {tag} - {e}")
        current_app.logger.exception(e)

        flash("There was an error while deleting your tag. Try again later.", "danger")
        return redirect(url_for("movie.add_tags", movieId=movieId))

    flash("Your tag has been deleted!", "success")
    return redirect(url_for("movie.movie", movieId=movieId))


@bp.route("/movie/<int:movieId>/watch", methods=["GET", "POST"])
@login_required
def watch_today(movieId):
    movie = Movie.query.get_or_404(movieId)
    last_watched = datetime.datetime.today()
    movie.last_seen = last_watched
    db.session.commit()
    return redirect(url_for("movie.movie", movieId=movie.id))


@bp.route("/movie/<int:movieId>/<int:new_rating>", methods=["GET", "POST"])
@login_required
def rate_movie(movieId, new_rating):
    movie = Movie.query.get_or_404(movieId)

    movie_rating = movie_rating_check(new_rating, movie)

    movie.rating = movie_rating
    db.session.commit()

    return redirect(url_for("movie.movie", movieId=movie.id))


@bp.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))


@bp.route("/", defaults={"path": ""})
@bp.route("/<path:path>")
def catch_all(path):
    return render_template("404.html"), 404

webapp/templates/home.html
{% extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movies.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock head_content %} {% block main_content %}
<div class="container">
  <header class="content-text">
    <h1>Welcome to the <strong>Flask User Management Example!</strong></h1>
    <p>
      <em>Need an account? </em
      ><a href="{{ url_for('auth.register') }}">Register!</a>
    </p>
    <p>
      <em>Existing user? </em><a href="{{ url_for('auth.login') }}">Login!</a>
    </p>
  </header>
</div>
{% endblock main_content %}

webapp/templates/layout.html
{% from "macros/_navbar.html" import header %} {% from "macros/_footer.html"
import footer %}

<!DOCTYPE html>
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title | default('Movie Watchlist') }}</title>
    <link
      href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/reset.css') }}"
    />

    {% block head_content %} {% endblock %}
  </head>

  <body>
    {{ header(current_user, session.get("theme")) }}

    <div class="messages">
      {% for message in get_flashed_messages() %}
      <div class="flash-message">
        <p>{{ message }}</p>
        <span class="close-btn" onclick="this.parentElement.style.opacity=0;">
          <svg
            width="12"
            height="12"
            version="1.1"
            viewBox="0 0 100 100"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="m49.941 35.891 33.531-33.531 14.168 14.168-33.531 33.414 33.531 33.531-14.168 14.168-33.531-33.531-33.414 33.531-14.168-14.168 33.531-33.531-33.531-33.414 14.168-14.168z"
              fill-rule="evenodd"
              fill="currentColor"
            />
          </svg>
        </span>
      </div>
      {% endfor %}
    </div>

    <div class="main">{% block main_content %} {% endblock main_content %}</div>

    {{ footer() }}
  </body>
</html>

webapp/templates/login.html
{% from "macros/fields.html" import render_text_field %} {% extends
'layout.html' %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock head_content %} {% block main_content %}

<form name="login" method="POST" class="form" novalidate action="">

  <div class="form_container">
    {{ form.hidden_tag() }} {{ render_text_field(form.email) }} {{
    render_text_field(form.password) }}

    <div class="container-center">
      <span class="form_small">
        Don't have an account?
        <a href="{{ url_for('auth.register') }}" class="form_link"
          >Register here</a
        >.
      </span>
    </div>

    <div class="container-center">
      {{ form.submit(class_="button button--form") }}
    </div>
  </div>
</form>

{% endblock main_content %}

webapp/templates/movie.html
{% extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movies.css') }}"
/>
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %} {% if movies_data %}

<table class="table">
  <colgroup>
    <col style="width: 60%" />
    <col style="width: 25%" />
    <col style="width: 15%" />
  </colgroup>
  <thead>
    <tr class="table__header">
      <th class="table_cell table_cell--header">Title</th>
      <th class="table_cell table_cell--header">Release Date</th>
      <th class="table_cell table_cell--header"></th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies_data %}
    <tr>
      <td class="table_cell">
        <p class="table_movieTitle">{{ movie.title }}</p>
        <p class="table_movieDirector">By {{ movie.director }}</p>
      </td>
      <td class="table_cell">{{ movie.year }}</td>
      <td class="table_cell">
        <a
          href="{{ url_for('movie.movie', movieId=movie.id) }}"
          class="table_link"
          >View</a
        >
        <a
          onclick="return confirm('Are you sure you want to delete this movie?');"
          href="{{ url_for('movie.delete_movie', movieId=movie.id) }}"
          class="table_link"
          >Delete</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% else %}
<p class="table_empty">
  You haven't added any movies yet.
  <a href="{{ url_for('movie.add_movie') }}" class="link">Add one!</a>
</p>
{% endif %}

<a href="{{ url_for('movie.add_movie') }}" class="button button--add">
  <span>+</span>
</a>

{% endblock %}

webapp/templates/movie_details.html
{% from "macros/svgs.html" import star, pencil, add, delete %}
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/movie_details.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="movie_header">

        <div class="header_row">
            <div class="movie_name">
                <h1>{{ movie.title }}</h1>
                <div class="movie_rating">
                    {% for i in range(5) %}
                        <a class="rating_link" href="{{ url_for('movie.rate_movie', movieId=movie.id, new_rating=i+1) }}">
                            {{ star("star " + ("star--filled" if movie.rating > i else "")) }}
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="movie_watched">
                {% if movie.last_seen %}
                    <p>
                        Last watched: <a href="{{ url_for('movie.watch_today', movieId=movie.id) }}" class="watched_link">
                            <time datetime="{{ movie.last_seen }}">{{movie.last_seen.strftime("%d %b %Y")}}</time>
                        </a>
                    </p>
                {% else %}
                    <p><a href="{{ url_for('movie.watch_today', movieId=movie.id) }}" class="watched_link">Not watched yet</a></p>
                {% endif %}
                <a class="movie_edit" href="{{ url_for('movie.edit_movie', movieId=movie.id) }}">Edit {{ pencil("pencil") }}</a>
            </div>
        </div>
        <div class="header_row">
            {% if tags %}
            <ul class="movie_tags">
                {% for tag in tags %}
                <li class="movie_tag">
                    <a  onclick="return confirm('Are you sure you want to delete this tag?');" 
                        href="{{ url_for('movie.delete_tag', movieId=movie.id, tag_id=tag.id) }}" 
                        class="tag_delete">{{ tag.tag }}</a></li>
            {% endfor %}
            </ul>
            <a class="tag_add" href="{{ url_for('movie.add_tags', movieId=movie.id) }}">Add  {{ add("add") }}</a>
            {% endif %}
        </div>
    </header>
    {% if movie.video_link %}
    <iframe
        class="movie_video"
        src="{{ movie.video_link }}"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

    {% if movie.description %}
        <p class="movie_description">{{ movie.description }}</p>
    {% else %}
        <p class="movie_description">No description yet. <a class="link" href="{{ url_for('movie.edit_movie', movieId=movie.id) }}">Add one?</a></p>
    {% endif %}
    
    <div class="movie_meta">
        {% if cast %}
            <div class="movie_casting">
                <h2>Casting</h2>
                <ul class="list">
                {% for actor in cast %}
                    <li class="list_item">{{ actor.actor }}</li>
                {% endfor %}
                <ul>
            </div>
        {% endif %}
        {% if series %}
        <div class="movie_series">
            <h2>Series</h2>
            <ul class="list">
            {% for movie_in_series in series %}
                <li class="list_item"><p class="list_item_box">{{ movie_in_series.series }}</p></li>
            {% endfor %}
            <ul>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

webapp/templates/movie_form.html
{% from "macros/fields.html" import render_text_field, render_area_field %} {%
extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<form name="add_movie" method="post" novalidate class="form">
  <div class="form_container">
    {{ form.hidden_tag() }} {{ render_text_field(form.title) }} {{
    render_text_field(form.director) }} {{ render_text_field(form.year) }} {{
    render_area_field(form.description) }} {{ render_text_field(form.video_link)
    }}
    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>

{% endblock %}

webapp/templates/new_movie.html
{% from "macros/fields.html" import render_text_field, render_area_field %} {%
extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<form name="add_movie" method="post" novalidate class="form">

  <div class="form_container">
    {{ form.hidden_tag() }} {{ render_text_field(form.title) }} {{
    render_text_field(form.director) }} {{ render_text_field(form.year) }} {{
    render_area_field(form.cast) }} {{ render_area_field(form.series) }} {{
    render_area_field(form.tags) }} {{ render_area_field(form.description) }} {{
    render_text_field(form.video_link) }}

    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>

{% endblock %}

webapp/templates/register.html
{% from "macros/fields.html" import render_text_field %} {% extends
'layout.html' %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock head_content %} {% block main_content %}

<form name="register" method="POST" class="form" novalidate action="">
  
  <div class="form_container">
    {{ form.hidden_tag() }} {{ render_text_field(form.email) }} {{
    render_text_field(form.password) }} {{
    render_text_field(form.confirm_password) }}

    <div class="container-center">
      <span class="form_small">
        Already have an account?
        <a href="{{ url_for('auth.login') }}" class="form_link">Log in here</a>.
      </span>
    </div>
    <div class="container-center">
      {{ form.submit(class_="button button--form") }}
    </div>
  </div>
</form>

{% endblock main_content %}

webapp/templates/status.html
{% extends "layout.html" %} {% block styling %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/user_profile_style.css') }}"
/>
{% endblock %} {% block content %}
<div class="card">
  <div class="card-heading">
    <h2>Status</h2>
  </div>
  <div class="card-body">
    <p>Web Application: Active</p>
    <p>Configuration Type: {{ config_type }}</p>
    <p>Database initialized: {{ database_status }}</p>
    <p>Database `user` table created: {{ database_users_table_status }}</p>
    <p>Database `movie` table created: {{ database_movies_table_status }}</p>
  </div>
</div>
{% endblock %}

webapp/templates/tag_form.html
{% from "macros/fields.html" import render_text_field, render_area_field %} {%
extends "layout.html" %} {%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<form name="add_movie" method="post" novalidate class="form">
  <div class="form_container">
    {{ form.hidden_tag() }} {{ render_area_field(form.tags) }}

    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>

{% endblock %}