webapp/movie/routes.py
import datetime

from pydantic import BaseModel, validator, ValidationError
from typing import Optional

from flask import current_app
from flask import Blueprint, redirect, render_template, session, url_for, request, flash, abort
from flask_login import current_user, login_required

from webapp import db
from webapp.models import Movie, User, Tag, Cast, Series
from webapp.movie.forms import MovieForm, EditMovieForm, AddTagsForm


bp = Blueprint("movie", __name__, template_folder="templates", static_folder="static")


# --------------
# Helper Classes
# --------------


class MovieModel(BaseModel):
    """Class for parsing new movie data from a form."""

    title: str
    director: str
    year: int
    description: Optional[str] = ""
    video_link: Optional[str] = ""


def movie_rating_check(value: int, movie: MovieModel) -> int:
    if value not in range(1, 6):
        error = "Movie rating must be a whole number between 1 and 5"
        current_app.logger.critical(f"Error while rating the movie: {movie.title} - {error}")
        abort(500, error)
    return value


@bp.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@bp.errorhandler(500)
def internal_error(e):
    return render_template("500.html"), 500


@bp.errorhandler(403)
def page_forbidden(e):
    return render_template("403.html"), 500


@bp.route("/")
def home():
    if current_user.is_authenticated:
        return redirect(url_for("movie.index"))

    return render_template("home.html")


@bp.route("/index")
@login_required
def index():
    if not current_user.is_authenticated:
        flash("You must be logged in to view your profile!", "danger")
        return redirect(url_for("auth.login"))

    try:
        movies = Movie.query.filter_by(userId=current_user.id).all()
    except Exception as error:
        current_app.logger.error("Error while getting movies from the database: {}".format(error))
        abort(404, error)

    return render_template("movie.html", title="Movies Watchlist", movies_data=movies)


@bp.route("/movie/<int:movieId>", methods=["GET"])
@login_required
def movie(movieId):
    current_app.logger.info("getting the movie from the database...")
    movie = Movie.query.get_or_404(movieId)

    try:
        current_app.logger.debug("Get tags, cast and series with index: {}".format(movieId))
        tags = Tag.query.filter_by(movieId=movie.id)
        cast = Cast.query.filter_by(movieId=movie.id)
        series = Series.query.filter_by(movieId=movie.id)

    except Exception as error:
        current_app.logger.error("MovieId {} is causing an IndexError".format(movieId))
        abort(404, error)

    return render_template("movie_details.html", movie=movie, tags=tags, cast=cast, series=series)


@bp.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    """Add a new movie to the database."""

    if not current_user.is_authenticated:
        flash("You must be logged in to add a movie!", "danger")
        return redirect(url_for("auth.login"))

    user = User.query.filter_by(id=current_user.id).first()
    form = MovieForm()

    if request.method == "POST":
        try:
            movie_data = MovieModel(title=form.title.data, director=form.director.data, year=form.year.data)
            movie = Movie(title=movie_data.title, director=movie_data.director, year=movie_data.year, userId=user.id)
            db.session.add(movie)
            db.session.commit()

        except ValidationError as e:
            flash("Error with movie data submitted!")
            db.session.rollback()

        if form.validate_on_submit():
            try:
                for actor in form.cast.data:
                    cast = Cast(actor=actor, movieId=movie.id)
                    db.session.add(cast)

                for tag in form.tags.data:
                    tag = Tag(tag=tag, movieId=movie.id)
                    db.session.add(tag)

                for serial in form.series.data:
                    single_serial = Series(series=serial, movieId=movie.id)
                    db.session.add(single_serial)

                if form.description.data != "":
                    movie.description = form.description.data

                if form.video_link.data != "":
                    movie.video_link = form.video_link.data

                db.session.commit()
                flash(f"Added new movie ({movie.title})!")
                current_app.logger.info(f"Movie ({movie.title}) was added for user: {current_user.id}!")
                return redirect(url_for("movie.index"))

            except Exception as error:
                db.session.rollback()
                current_app.logger.error("MovieId {} is causing an IndexError".format(movieId))
                abort(404, error)

    return render_template("new_movie.html", title="Movies Watchlist - Add Movie", form=form)


@bp.route("/edit/<int:movieId>", methods=["GET", "POST"])
@login_required
def edit_movie(movieId):
    """Edit a movie in the database."""

    movie = Movie.query.get_or_404(movieId)
    form = EditMovieForm(obj=movie)

    if movie is None:
        abort(404)

    if movie.userId != current_user.id:
        abort(500)

    if form.validate_on_submit():
        try:
            movie.title = form.title.data
            movie.director = form.director.data
            movie.year = form.year.data
            movie.description = form.description.data
            movie.video_link = form.video_link.data

            db.session.commit()

        except Exception as e:
            db.session.rollback()
            current_app.logger.critical(f"Error while editing the movie: {movie.title} - {e}")
            current_app.logger.exception(e)
            flash("There was an error while editing your movie. Try again later.", "danger")
            return redirect(url_for("movie.edit_movie", movieId=movie.id))

        flash("The movie has been updated successfully!", "success")
        return redirect(url_for("movie.movie", movieId=movie.id))

    return render_template("movie_form.html", movie=movie, form=form)


@bp.route("/<int:movieId>/delete")
@login_required
def delete_movie(movieId):
    movie = Movie.query.get_or_404(movieId)

    if movie is None:
        abort(404)

    if movie.userId != current_user.id:
        abort(403)

    db.session.delete(movie)
    db.session.commit()
    flash(f"Movie ({movie.title}) was deleted!")
    current_app.logger.info(f"Movie ({movie.title}) was deleted for user: {current_user.id}!")

    return redirect(url_for("movie.index"))


@bp.route("/add/tags/<int:movieId>", methods=["GET", "POST"])
@login_required
def add_tags(movieId):
    tags = Tag.query.filter_by(movieId=movieId)
    form = AddTagsForm()

    if form.validate_on_submit():
        try:
            for tag in form.tags.data:
                tag = Tag(tag=tag, movieId=movieId)
                db.session.add(tag)
            db.session.commit()

        except Exception as e:
            db.session.rollback()
            current_app.logger.critical(f"Error while adding the tag: {tag} - {e}")
            current_app.logger.exception(e)

            flash("There was an error while adding your tag. Try again later.", "danger")
            return redirect(url_for("movie.add_tags", movieId=movieId))

        flash("Your tag has been added!", "success")
        return redirect(url_for("movie.movie", movieId=movieId))

    return render_template("tag_form.html", tags=tags, form=form)


@bp.route("/movie/<int:movieId>/delete/tags/<int:tag_id>", methods=["GET", "POST"])
@login_required
def delete_tag(tag_id, movieId):
    tag = Tag.query.filter_by(id=tag_id).first_or_404()

    try:
        db.session.delete(tag)
        db.session.commit()

    except Exception as e:
        db.session.rollback()
        current_app.logger.critical(f"Error while deleting the tag: {tag} - {e}")
        current_app.logger.exception(e)

        flash("There was an error while deleting your tag. Try again later.", "danger")
        return redirect(url_for("movie.add_tags", movieId=movieId))

    flash("Your tag has been deleted!", "success")
    return redirect(url_for("movie.movie", movieId=movieId))


@bp.route("/movie/<int:movieId>/watch", methods=["GET", "POST"])
@login_required
def watch_today(movieId):
    movie = Movie.query.get_or_404(movieId)
    last_watched = datetime.datetime.today()
    movie.last_seen = last_watched
    db.session.commit()
    return redirect(url_for("movie.movie", movieId=movie.id))


@bp.route("/movie/<int:movieId>/<int:new_rating>", methods=["GET", "POST"])
@login_required
def rate_movie(movieId, new_rating):
    movie = Movie.query.get_or_404(movieId)

    movie_rating = movie_rating_check(new_rating, movie)

    movie.rating = movie_rating
    db.session.commit()

    return redirect(url_for("movie.movie", movieId=movie.id))


@bp.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))


@bp.route("/", defaults={"path": ""})
@bp.route("/<path:path>")
def catch_all(path):
    return render_template("404.html"), 404

webapp/templates/macros/_footer.html
{% macro footer() %}

<footer class="footer">
  <small>Copyright &copy;2022. Movies Watchlist. All rights reserved.</small>
</footer>

{% endmacro %}

webapp/templates/macros/_navbar.html
{% from "macros/svgs.html" import moon, sun %} {% macro header(current_user,
theme) %}

<header class="header">
  <div class="nav-container">
    <a href="{{ url_for('movie.index') }}" class="header_logo">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="logo_icon"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z"
        />
      </svg>
      <span class="logo_name">Watchlist</span>
    </a>
    <nav class="nav">
      {% if current_user.is_authenticated %}
      <a
        href="{{ url_for('movie.index') }}"
        class="nav_link {{ 'nav_link--active' if request.path == url_for('movie.index') }}"
      >
        <span class="nav_item">Movies</span>
      </a>
      <a href="{{ url_for('auth.logout') }}" class="nav_link">
        <span class="nav_item">Log out</span>
      </a>
      {% else %}
      <a
        href="{{ url_for('auth.login') }}"
        class="nav_link {{ 'nav_link--active' if request.path == url_for('auth.login') }}"
      >
        <span class="nav_item">Log in</span>
      </a>
      <a
        href="{{ url_for('auth.register') }}"
        class="nav_link {{ 'nav_link--active' if request.path == url_for('auth.register') }}"
      >
        <span class="nav_item">Register</span>
      </a>
      {% endif %}
      <a
        href="{{ url_for('movie.toggle_theme', current_page=request.path) }}"
        class="nav_link"
      >
        <span class="nav_item">
          {% if theme == "dark" %} {{ sun("nav_icon") }} {% else %} {{
          moon("nav_icon") }} {% endif %}
        </span>
      </a>
    </nav>
  </div>
</header>
{% endmacro %}

webapp/templates/macros/fields.html
{% macro render_text_field(field) %}

<div class="form_group">
  {{ field.label(class_="form_label") }} {{ field(class_="form_field",
  id="{{field}}") }} {% for error in field.errors %}
  <span class="form_error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %} {% macro render_area_field(field) %}
<div class="form_group">
  {{ field.label(class_="form_label") }} {{ field(rows=4, class_="form_field",
  style="resize: none") }} {% for error in field.errors %}
  <span class="form_error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %}

webapp/templates/macros/svgs.html
{% macro star(class_) %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  class="{{ class_ }}"
  viewBox="0 0 24 24"
  stroke="currentColor"
>
  <path
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
    d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z"
  />
</svg>
{% endmacro %} {% macro pencil(class_) %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  class="{{ class_ }}"
  fill="none"
  viewBox="0 0 24 24"
  stroke="currentColor"
>
  <path
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"
  />
</svg>
{% endmacro %} {% macro moon(class_) %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  class="{{ class_ }}"
  fill="none"
  viewBox="0 0 24 24"
  stroke="currentColor"
>
  <path
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
    d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z"
  />
</svg>
{% endmacro %} {% macro sun(class_) %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  class="{{ class_ }}"
  fill="none"
  viewBox="0 0 24 24"
  stroke="currentColor"
>
  <path
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
    d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z"
  />
</svg>
{% endmacro %} {% macro add(class_) %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  class="{{ class_ }}"
  viewBox="0 0 24 24"
>
  <path
    d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
  />
  <path
    d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"
  />
</svg>
{% endmacro %} {% macro delete(class_) %}
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  fill="currentColor"
  class="bi bi-x-circle"
  viewBox="0 0 24 24"
>
  <path
    d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
  />
  <path
    stroke-linecap="round"
    stroke-linejoin="round"
    stroke-width="2"
    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"
  />
</svg>
{% endmacro %}